spring.application.name=foodDelivery
server.port=8080

spring.messages.basename=lang.messages
spring.messages.cache-duration=1800
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5432/foodDeliveryDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jooq.sql-dialect=postgres