spring.application.name=foodDelivery
server.port=8080

spring.messages.basename=lang.messages
spring.messages.cache-duration=1800
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5432/foodDeliveryDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.sql.init.mode=never
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

spring.jooq.sql-dialect=postgres

#spring.liquibase.enabled=false
#spring.liquibase.change-log=classpath:db/changelog/changelog.xml

#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true
#spring.flyway.placeholder-replacement=false

#spring.cassandra.contact-points=localhost
#spring.cassandra.port=9042
#spring.cassandra.keyspace-name=foodDeliveryCassandra
#spring.cassandra.username=cassandra
#spring.cassandra.password=cassandra
#spring.cassandra.local-datacenter=datacenter1
#spring.cassandra.connection.init-query-timeout=5s
#spring.cassandra.request.timeout=5s
#spring.cassandra.schema-action=create_if_not_exists

#spring.mongodb.uri=mongodb://localhost:27017/foodDeliveryMongo?uuidRepresentation=STANDARD
#spring.mongodb.database=foodDeliveryMongo

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=12345678