CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255)        NOT NULL,
    email    VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    telegram VARCHAR(255)        NOT NULL,
    phone    VARCHAR(255)        NOT NULL,
    address  VARCHAR(255)        NOT NULL
);

CREATE TABLE IF NOT EXISTS menu_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)   NOT NULL,
    menu_category VARCHAR(255)   NOT NULL,
    price         DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date  TIMESTAMP      NOT NULL,
    status      VARCHAR(255)   NOT NULL,
    user_id     BIGINT         NOT NULL REFERENCES users (id),
    total_price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders_menu_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT REFERENCES orders (id),
    menu_item_id BIGINT REFERENCES menu_items (id)
);

CREATE TABLE IF NOT EXISTS deliveries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address       VARCHAR(255) NOT NULL,
    phone         VARCHAR(255) NOT NULL,
    delivery_time TIMESTAMP    NOT NULL,
    order_id      BIGINT       NOT NULL REFERENCES orders (id)
);